version: "3.4"
services:
    caddy:
        build:
            context: .
            target: prod
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ".caddy:/root/.caddy"
            - "./srv:/srv:ro"