version: "3.4"
services:
    caddy:
        build:
            target: dev
        volumes:
            - "./Caddyfile:/etc/Caddyfile:ro"
            - "./Caddyfile.comm:/etc/Caddyfile.comm:ro"
            - ".caddy:/root/.caddy"
            - "./srv:/srv:ro"